language: java
env:
  global:
    - secure: DIMKbCAWyfwXKXtSGw5EO3S+cZemH/k2LDeB8lEcYkeHSauGAHSskYI0hIt+9LVil7mUoLKKKWWR6Wb/uFiTylJasJMYab10qfWGvv/BhxYlLiTF2P3G1laonw5XGsfCE6y83K42AChsxKkQ2i51uYfJRjGiHDoAeBhV9nAbp5w=
before_script:
  - curl -L http://sourceforge.net/projects/saxon/files/Saxon-HE/9.5/SaxonHE9-5-1-4J.zip/download > SaxonHE9.zip
  - unzip SaxonHE9.zip
  - git config --global user.email "ci-server@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git config --global credential.helper "store --file=.git/credentials"

script:
  - java -jar saxon9he.jar -s:ucr-doc/wot-ucr.xml -o:wot-ucr-tmp.html -a -dtd

after_success:
  - git clone --branch gh-pages https://github.com/w3c/wot.git page
  - cp wot-ucr-tmp.html page/wot-ucr.html
  - cp tech-landscape/landscape.html page/landscape.html
  - cp -R current-practices/ page/
  - cp -R architecture/ page/
  - cp -R charters/ page/
  - mkdir -p page/proposals/explicit-bindings
  - cp  proposals/explicit-bindings/abstract-transfer-layer.html page/proposals/explicit-bindings/abstract-transfer-layer.html
  - cd page
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add wot-ucr.html
  - git add landscape.html
  - git add current-practices/
  - git add architecture/
  - git add charters/
  - git add proposals/explicit-bindings/abstract-transfer-layer.html
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then git diff-index --quiet --cached HEAD || git commit -m"automated commit from Travis CI"; fi
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then git push https://github.com/w3c/wot.git gh-pages; fi
